---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Dropbox/Development/GitHub/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - doxygen
  - gettext
  - gifsicle
  - git
  - go
  - gpg
  - hub
  - httpie
  - iperf
  - libevent
  - sqlite
  - mcrypt
  - nmap
  - node
  - nvm
  - php
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - pv
  - wget
  - wrk
  - fzf
  - mysql
  - yarn

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - docker
  - dropbox
  - firefox
  - google-chrome
  - handbrake
  - licecap
  - limechat
  - macvim
  - sequel-pro
  - skitch
  - slack
  - sublime-text
  - transmit
  - vagrant
  - virtualbox
  - phpstorm
  - google-chrome
  - alfred
  - google-backup-and-sync

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - 417375580 # BetterSnapTool
  - 1125725441 # Nimbus
  - 967004861 # HP Easy Scan
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages:
  - name: drush
    state: present
    version: "^9.4"
  - name: robo
    state: present
    version: "~1"
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages:
  - name: gulp-cli
pip_packages:
  - name: awscli

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []

zsh_antigen_bundles_extras:
  - nvm
  - joel-porquet/zsh-dircolors-solarized
zsh_autosuggestions_bind_key: "`"
